name: Create and Notify DNS Record

on:
  push:
    branches:
      - main  # Replace with your branch name
  workflow_dispatch:

jobs:
  delete-dns-record:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: CloudFlare Remove DNS Record
      uses: ScottRocha/remove-dns-record@v2.2
      with:
        id: ${{ secrets.RECORD_ID }}
        token: ${{ secrets.API_TOKEN }}
        zone: ${{ secrets.ZONE_ID }}
