name: Create and Notify DNS Record

on:
  push:
    branches:
      - main  # Replace with your branch name
  workflow_dispatch:

jobs:
  create-dns-record:
    runs-on: ubuntu-latest
    steps:
    - name: Show Available Records
      run: |
        CF_API_TOKEN="HsoabgfSbNQVeHpg30hI14GOo8mZLixzk_7HhJY8"
        ZONE_ID="38b42bfdb42dbe301b6b1a27b86ac939"

        API_URL="https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records"

        curl -s -H "Authorization: Bearer $CF_API_TOKEN" "$API_URL" | jq .
