name: Cloudflare DNS Update and Fetch

on:
  push:
    branches:
      - dns-create-practice
  workflow_dispatch:

jobs:
  update-dns-record-and-fetch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set DNS Details
      run: |
        RECORD_NAME="saadiqbal.karazo.com"
        RECORD_TYPE="CNAME"
        RECORD_CONTENT="192.168.18.250"
        echo "RECORD_NAME=$RECORD_NAME" >> $GITHUB_ENV
        echo "RECORD_TYPE=$RECORD_TYPE" >> $GITHUB_ENV
        echo "RECORD_CONTENT=$RECORD_CONTENT" >> $GITHUB_ENV

    - name: Create or Update DNS Record
      run: |
        CF_API_TOKEN="HsoabgfSbNQVeHpg30hI14GOo8mZLixzk_7HhJY8"
        ZONE_ID="38b42bfdb42dbe301b6b1a27b86ac939"
        RECORD_NAME="saaddemo.karazo.com"
        RECORD_TYPE="CNAME"
        RECORD_CONTENT="192.168.18.250"
        TTL=3600
        DNS_COMMENT="Domain verification record"
        
        API_URL="https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records"
        EXISTING_DNS_RECORD=$(curl -s -H "Authorization: Bearer $CF_API_TOKEN" "$API_URL?type=$RECORD_TYPE&name=$RECORD_NAME")
        
        if [[ "$EXISTING_DNS_RECORD" == "[]" ]]; then
          curl -X POST "$API_URL" \
               -H "Authorization: Bearer $CF_API_TOKEN" \
               -H "Content-Type: application/json" \
               --data "{
                 \"type\": \"$RECORD_TYPE\",
                 \"name\": \"$RECORD_NAME\",
                 \"content\": \"$RECORD_CONTENT\",
                 \"ttl\": $TTL,
                 \"comment\": \"$DNS_COMMENT\"
               }"
          echo "DNS record created."
        else
          DNS_RECORD_ID=$(echo "$EXISTING_DNS_RECORD" | jq -r '.result[0].id')
          curl -X PUT "$API_URL/$DNS_RECORD_ID" \
               -H "Authorization: Bearer $CF_API_TOKEN" \
               -H "Content-Type: application/json" \
               --data "{
                 \"type\": \"$RECORD_TYPE\",
                 \"name\": \"$RECORD_NAME\",
                 \"content\": \"$RECORD_CONTENT\",
                 \"ttl\": $TTL,
                 \"comment\": \"$DNS_COMMENT\"
               }"
          echo "DNS record updated."
        fi

    - name: Fetch All DNS Records
      run: |
        CF_API_TOKEN="HsoabgfSbNQVeHpg30hI14GOo8mZLixzk_7HhJY8"
        ZONE_ID="38b42bfdb42dbe301b6b1a27b86ac939"
        
        API_URL="https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records"
        ALL_DNS_RECORDS=$(curl -s -H "Authorization: Bearer $CF_API_TOKEN" "$API_URL")
        
        echo "$ALL_DNS_RECORDS" > all_dns_records.json
