name: Create DNS Record

on:
  push:
    branches:
      - main  # Replace with your branch name
  workflow_dispatch:

jobs:
  create-dns-record:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt-get update
        sudo apt-get install python3

    - name: Create DNS Record
      run: python3 create_dns_record.py
