name: Create DNS Record

on:
  push:
    branches:
      - main  # Replace with your branch name
  workflow_dispatch:

jobs:
  create-dns-record:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install python3

      - name: Run python-scripts.py
        run: |
          python3 python-scripts.py
